import type { Train, User, Booking } from './types';

export const stations = [
  'New Delhi, DL',
  'Mumbai Central, MH',
  'Chennai Central, TN',
  'Howrah Junction, WB',
  'Bengaluru City, KA',
  'Secunderabad Jn, TS',
  'Pune Junction, MH',
  'Ahmedabad Junction, GJ',
];

export const trains: Train[] = [
  // 1. New Delhi -> Mumbai Central
  {
    id: 'TM101',
    name: 'Delhi-Mumbai Rajdhani',
    number: '12952',
    from: 'New Delhi, DL',
    to: 'Mumbai Central, MH',
    departureTime: '16:55',
    arrivalTime: '08:15',
    duration: '15h 20m',
    classes: [
      { name: 'Economy', availability: 145, price: 2150 },
      { name: 'Business', availability: 35, price: 3550 },
      { name: 'First', availability: 8, price: 5450 },
    ],
  },
  {
    id: 'TM102',
    name: 'Delhi-Mumbai Duronto',
    number: '22210',
    from: 'New Delhi, DL',
    to: 'Mumbai Central, MH',
    departureTime: '23:25',
    arrivalTime: '15:50',
    duration: '16h 25m',
    classes: [
      { name: 'Economy', availability: 210, price: 1950 },
      { name: 'Business', availability: 50, price: 3300 },
      { name: 'First', availability: 12, price: 4800 },
    ],
  },
  // 2. Mumbai Central -> New Delhi
  {
    id: 'T123',
    name: 'Mumbai Rajdhani',
    number: '12951',
    from: 'Mumbai Central, MH',
    to: 'New Delhi, DL',
    departureTime: '17:00',
    arrivalTime: '08:30',
    duration: '15h 30m',
    classes: [
      { name: 'Economy', availability: 150, price: 2100 },
      { name: 'Business', availability: 40, price: 3500 },
      { name: 'First', availability: 10, price: 5400 },
    ],
  },
  {
    id: 'T124',
    name: 'August Kranti Rajdhani',
    number: '12953',
    from: 'Mumbai Central, MH',
    to: 'New Delhi, DL',
    departureTime: '17:10',
    arrivalTime: '10:55',
    duration: '17h 45m',
    classes: [
      { name: 'Economy', availability: 120, price: 2000 },
      { name: 'Business', availability: 30, price: 3300 },
      { name: 'First', availability: 5, price: 5200 },
    ],
  },
   // 3. New Delhi -> Chennai Central
  {
    id: 'TM201',
    name: 'Tamil Nadu Express',
    number: '12622',
    from: 'New Delhi, DL',
    to: 'Chennai Central, TN',
    departureTime: '21:05',
    arrivalTime: '06:15',
    duration: '33h 10m',
    classes: [
        { name: 'Economy', availability: 250, price: 1100 },
        { name: 'Business', availability: 70, price: 2800 },
        { name: 'First', availability: 20, price: 4800 },
    ],
  },
  {
    id: 'TM202',
    name: 'Delhi-Chennai Rajdhani',
    number: '12434',
    from: 'New Delhi, DL',
    to: 'Chennai Central, TN',
    departureTime: '15:35',
    arrivalTime: '20:45',
    duration: '29h 10m',
    classes: [
        { name: 'Economy', availability: 180, price: 2500 },
        { name: 'Business', availability: 60, price: 4100 },
        { name: 'First', availability: 18, price: 6300 },
    ],
  },
  // 4. Chennai Central -> New Delhi
  {
    id: 'T601',
    name: 'Grand Trunk Express',
    number: '12615',
    from: 'Chennai Central, TN',
    to: 'New Delhi, DL',
    departureTime: '18:50',
    arrivalTime: '05:05',
    duration: '34h 15m',
    classes: [
        { name: 'Economy', availability: 250, price: 1000 },
        { name: 'Business', availability: 80, price: 2500 },
        { name: 'First', availability: 20, price: 4500 },
    ],
  },
  {
    id: 'T212',
    name: 'Chennai Rajdhani',
    number: '12433',
    from: 'Chennai Central, TN',
    to: 'New Delhi, DL',
    departureTime: '06:05',
    arrivalTime: '10:30',
    duration: '28h 25m',
    classes: [
      { name: 'Economy', availability: 0, price: 2400 },
      { name: 'Business', availability: 60, price: 4000 },
      { name: 'First', availability: 15, price: 6200 },
    ],
  },
  // 5. New Delhi -> Howrah Junction
  {
    id: 'T789R',
    name: 'Delhi-Howrah Rajdhani',
    number: '12302',
    from: 'New Delhi, DL',
    to: 'Howrah Junction, WB',
    departureTime: '16:55',
    arrivalTime: '09:55',
    duration: '17h 00m',
    classes: [
        { name: 'Economy', availability: 10, price: 2250 },
        { name: 'Business', availability: 20, price: 3850 },
        { name: 'First', availability: 10, price: 5850 },
    ],
  },
  {
    id: 'T790R',
    name: 'Poorva Express Return',
    number: '12304',
    from: 'New Delhi, DL',
    to: 'Howrah Junction, WB',
    departureTime: '17:40',
    arrivalTime: '17:00',
    duration: '23h 20m',
    classes: [
      { name: 'Economy', availability: 280, price: 870 },
      { name: 'Business', availability: 90, price: 1550 },
      { name: 'First', availability: 25, price: 2850 },
    ],
  },
  // 6. Howrah Junction -> New Delhi
  {
    id: 'T789',
    name: 'Howrah Rajdhani',
    number: '12301',
    from: 'Howrah Junction, WB',
    to: 'New Delhi, DL',
    departureTime: '16:50',
    arrivalTime: '10:00',
    duration: '17h 10m',
    classes: [
      { name: 'Economy', availability: 5, price: 2200 },
      { name: 'Business', availability: 25, price: 3800 },
      { name: 'First', availability: 8, price: 5800 },
    ],
  },
  {
    id: 'T790',
    name: 'Poorva Express',
    number: '12303',
    from: 'Howrah Junction, WB',
    to: 'New Delhi, DL',
    departureTime: '08:00',
    arrivalTime: '06:00',
    duration: '22h 00m',
    classes: [
      { name: 'Economy', availability: 300, price: 850 },
      { name: 'Business', availability: 100, price: 1500 },
      { name: 'First', availability: 30, price: 2800 },
    ],
  },
  // 7. New Delhi -> Bengaluru City
  {
    id: 'T456R',
    name: 'Delhi-Bengaluru Rajdhani',
    number: '22692',
    from: 'New Delhi, DL',
    to: 'Bengaluru City, KA',
    departureTime: '20:45',
    arrivalTime: '06:40',
    duration: '33h 55m',
    classes: [
        { name: 'Economy', availability: 180, price: 2550 },
        { name: 'Business', availability: 45, price: 4250 },
        { name: 'First', availability: 12, price: 6050 },
    ],
  },
  {
    id: 'T457R',
    name: 'Karnataka Express Return',
    number: '12628',
    from: 'New Delhi, DL',
    to: 'Bengaluru City, KA',
    departureTime: '20:20',
    arrivalTime: '13:40',
    duration: '41h 20m',
    classes: [
      { name: 'Economy', availability: 15, price: 980 },
      { name: 'Business', availability: 8, price: 1950 },
      { name: 'First', availability: 3, price: 3450 },
    ],
  },
  // 8. Bengaluru City -> New Delhi
  {
    id: 'T456',
    name: 'Bengaluru Rajdhani',
    number: '22691',
    from: 'Bengaluru City, KA',
    to: 'New Delhi, DL',
    departureTime: '20:00',
    arrivalTime: '05:30',
    duration: '33h 30m',
    classes: [
      { name: 'Economy', availability: 200, price: 2500 },
      { name: 'Business', availability: 50, price: 4200 },
      { name: 'First', availability: 0, price: 6000 },
    ],
  },
  {
    id: 'T457',
    name: 'Karnataka Express',
    number: '12627',
    from: 'Bengaluru City, KA',
    to: 'New Delhi, DL',
    departureTime: '19:20',
    arrivalTime: '09:00',
    duration: '37h 40m',
    classes: [
      { name: 'Economy', availability: 10, price: 950 },
      { name: 'Business', availability: 5, price: 1900 },
      { name: 'First', availability: 2, price: 3400 },
    ],
  },
  // 9. New Delhi -> Secunderabad Jn
  {
    id: 'T101R',
    name: 'Delhi-Secunderabad Duronto',
    number: '12286',
    from: 'New Delhi, DL',
    to: 'Secunderabad Jn, TS',
    departureTime: '15:55',
    arrivalTime: '14:50',
    duration: '22h 55m',
    classes: [
      { name: 'Economy', availability: 70, price: 1850 },
      { name: 'Business', availability: 15, price: 3250 },
      { name: 'First', availability: 4, price: 5050 },
    ],
  },
  {
    id: 'TM301',
    name: 'Telangana Express',
    number: '12724',
    from: 'New Delhi, DL',
    to: 'Secunderabad Jn, TS',
    departureTime: '17:25',
    arrivalTime: '19:30',
    duration: '26h 05m',
    classes: [
      { name: 'Economy', availability: 200, price: 900 },
      { name: 'Business', availability: 60, price: 2400 },
    ],
  },
  // 10. Secunderabad Jn -> New Delhi
  {
    id: 'T101',
    name: 'Duronto Express',
    number: '12285',
    from: 'Secunderabad Jn, TS',
    to: 'New Delhi, DL',
    departureTime: '12:50',
    arrivalTime: '10:35',
    duration: '21h 45m',
    classes: [
      { name: 'Economy', availability: 80, price: 1800 },
      { name: 'Business', availability: 20, price: 3200 },
      { name: 'First', availability: 5, price: 5000 },
    ],
  },
  {
    id: 'TM302',
    name: 'Telangana Express',
    number: '12723',
    from: 'Secunderabad Jn, TS',
    to: 'New Delhi, DL',
    departureTime: '06:25',
    arrivalTime: '09:05',
    duration: '26h 40m',
    classes: [
      { name: 'Economy', availability: 220, price: 920 },
      { name: 'Business', availability: 55, price: 2450 },
    ],
  },
  // 11. New Delhi -> Pune Junction
  {
    id: 'TM401',
    name: 'Delhi-Pune Duronto',
    number: '12264',
    from: 'New Delhi, DL',
    to: 'Pune Junction, MH',
    departureTime: '10:55',
    arrivalTime: '07:10',
    duration: '20h 15m',
    classes: [
      { name: 'Economy', availability: 100, price: 1700 },
      { name: 'Business', availability: 30, price: 3000 },
      { name: 'First', availability: 10, price: 4500 },
    ],
  },
  {
    id: 'TM402',
    name: 'Goa Express',
    number: '12780',
    from: 'New Delhi, DL',
    to: 'Pune Junction, MH',
    departureTime: '15:00',
    arrivalTime: '22:20',
    duration: '31h 20m',
    classes: [
      { name: 'Economy', availability: 150, price: 950 },
      { name: 'Business', availability: 40, price: 2500 },
    ],
  },
  // 12. Pune Junction -> New Delhi
  {
    id: 'TM403',
    name: 'Pune-Delhi Duronto',
    number: '12263',
    from: 'Pune Junction, MH',
    to: 'New Delhi, DL',
    departureTime: '11:10',
    arrivalTime: '06:45',
    duration: '19h 35m',
    classes: [
      { name: 'Economy', availability: 90, price: 1750 },
      { name: 'Business', availability: 25, price: 3050 },
      { name: 'First', availability: 8, price: 4550 },
    ],
  },
  // 13. New Delhi -> Ahmedabad Junction
  {
    id: 'TM501',
    name: 'Ashram Express',
    number: '12916',
    from: 'New Delhi, DL',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '14:55',
    arrivalTime: '06:20',
    duration: '15h 25m',
    classes: [
      { name: 'Economy', availability: 300, price: 750 },
      { name: 'Business', availability: 80, price: 1800 },
    ],
  },
  // 14. Ahmedabad Junction -> New Delhi
  {
    id: 'TM502',
    name: 'Ashram Express',
    number: '12915',
    from: 'Ahmedabad Junction, GJ',
    to: 'New Delhi, DL',
    departureTime: '19:15',
    arrivalTime: '10:00',
    duration: '14h 45m',
    classes: [
      { name: 'Economy', availability: 280, price: 760 },
      { name: 'Business', availability: 70, price: 1820 },
    ],
  },
  // 15. Mumbai Central -> Chennai Central
  {
    id: 'TM601',
    name: 'Mumbai-Chennai Express',
    number: '22159',
    from: 'Mumbai Central, MH',
    to: 'Chennai Central, TN',
    departureTime: '12:45',
    arrivalTime: '10:45',
    duration: '22h 00m',
    classes: [
      { name: 'Economy', availability: 200, price: 900 },
      { name: 'Business', availability: 60, price: 2300 },
    ],
  },
  // 16. Chennai Central -> Mumbai Central
  {
    id: 'TM602',
    name: 'Chennai-Mumbai Express',
    number: '22160',
    from: 'Chennai Central, TN',
    to: 'Mumbai Central, MH',
    departureTime: '13:15',
    arrivalTime: '12:00',
    duration: '22h 45m',
    classes: [
      { name: 'Economy', availability: 180, price: 920 },
      { name: 'Business', availability: 50, price: 2350 },
    ],
  },
  // 17. Mumbai Central -> Howrah Junction
  {
    id: 'TM701',
    name: 'Mumbai Mail (via Nagpur)',
    number: '12322',
    from: 'Mumbai Central, MH',
    to: 'Howrah Junction, WB',
    departureTime: '22:15',
    arrivalTime: '11:40',
    duration: '37h 25m',
    classes: [
      { name: 'Economy', availability: 150, price: 1200 },
      { name: 'Business', availability: 40, price: 3000 },
    ],
  },
  // 18. Howrah Junction -> Mumbai Central
  {
    id: 'TM702',
    name: 'Howrah Mail (via Nagpur)',
    number: '12321',
    from: 'Howrah Junction, WB',
    to: 'Mumbai Central, MH',
    departureTime: '22:00',
    arrivalTime: '13:15',
    duration: '39h 15m',
    classes: [
      { name: 'Economy', availability: 140, price: 1250 },
      { name: 'Business', availability: 35, price: 3050 },
    ],
  },
  // 19. Mumbai Central -> Bengaluru City
  {
    id: 'TM801',
    name: 'Udyan Express',
    number: '11301',
    from: 'Mumbai Central, MH',
    to: 'Bengaluru City, KA',
    departureTime: '08:10',
    arrivalTime: '08:50',
    duration: '24h 40m',
    classes: [
      { name: 'Economy', availability: 180, price: 850 },
      { name: 'Business', availability: 50, price: 2200 },
    ],
  },
  // 20. Bengaluru City -> Mumbai Central
  {
    id: 'TM802',
    name: 'Udyan Express',
    number: '11302',
    from: 'Bengaluru City, KA',
    to: 'Mumbai Central, MH',
    departureTime: '20:30',
    arrivalTime: '19:45',
    duration: '23h 15m',
    classes: [
      { name: 'Economy', availability: 170, price: 860 },
      { name: 'Business', availability: 45, price: 2250 },
    ],
  },
  // 21. Mumbai Central -> Secunderabad Jn
  {
    id: 'TM901',
    name: 'Devagiri Express',
    number: '17057',
    from: 'Mumbai Central, MH',
    to: 'Secunderabad Jn, TS',
    departureTime: '21:30',
    arrivalTime: '14:45',
    duration: '17h 15m',
    classes: [
      { name: 'Economy', availability: 120, price: 700 },
      { name: 'Business', availability: 30, price: 1800 },
    ],
  },
  // 22. Secunderabad Jn -> Mumbai Central
  {
    id: 'TM902',
    name: 'Devagiri Express',
    number: '17058',
    from: 'Secunderabad Jn, TS',
    to: 'Mumbai Central, MH',
    departureTime: '13:25',
    arrivalTime: '07:10',
    duration: '17h 45m',
    classes: [
      { name: 'Economy', availability: 110, price: 720 },
      { name: 'Business', availability: 25, price: 1850 },
    ],
  },
  // 23. Mumbai Central -> Pune Junction
  {
    id: 'TM1001',
    name: 'Indrayani Express',
    number: '22105',
    from: 'Mumbai Central, MH',
    to: 'Pune Junction, MH',
    departureTime: '05:40',
    arrivalTime: '09:05',
    duration: '3h 25m',
    classes: [
      { name: 'Economy', availability: 400, price: 450 },
      { name: 'Business', availability: 80, price: 900 },
    ],
  },
  {
    id: 'TM1002',
    name: 'Deccan Queen',
    number: '12123',
    from: 'Mumbai Central, MH',
    to: 'Pune Junction, MH',
    departureTime: '17:10',
    arrivalTime: '20:25',
    duration: '3h 15m',
    classes: [
      { name: 'Economy', availability: 350, price: 500 },
      { name: 'Business', availability: 70, price: 1000 },
    ],
  },
  // 24. Pune Junction -> Mumbai Central
  {
    id: 'TM1003',
    name: 'Indrayani Express',
    number: '22106',
    from: 'Pune Junction, MH',
    to: 'Mumbai Central, MH',
    departureTime: '18:35',
    arrivalTime: '22:00',
    duration: '3h 25m',
    classes: [
      { name: 'Economy', availability: 380, price: 460 },
      { name: 'Business', availability: 75, price: 920 },
    ],
  },
  {
    id: 'TM1004',
    name: 'Deccan Queen',
    number: '12124',
    from: 'Pune Junction, MH',
    to: 'Mumbai Central, MH',
    departureTime: '07:15',
    arrivalTime: '10:25',
    duration: '3h 10m',
    classes: [
      { name: 'Economy', availability: 340, price: 510 },
      { name: 'Business', availability: 65, price: 1020 },
    ],
  },
  // 25. Mumbai Central -> Ahmedabad Junction
  {
    id: 'T502R',
    name: 'Mumbai-Ahmedabad Shatabdi',
    number: '12010',
    from: 'Mumbai Central, MH',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '17:30',
    arrivalTime: '23:55',
    duration: '6h 25m',
    classes: [
        { name: 'Economy', availability: 100, price: 1150 },
        { name: 'Business', availability: 35, price: 2250 },
        { name: 'First', availability: 8, price: 3350 },
    ],
  },
  {
    id: 'T503R',
    name: 'Karnavati Express Return',
    number: '12933',
    from: 'Mumbai Central, MH',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '14:05',
    arrivalTime: '21:05',
    duration: '7h 00m',
    classes: [
        { name: 'Economy', availability: 190, price: 620 },
        { name: 'Business', availability: 45, price: 1350 },
    ],
  },
  // 26. Ahmedabad Junction -> Mumbai Central
  {
    id: 'T502',
    name: 'Ahmedabad-Mumbai Shatabdi',
    number: '12009',
    from: 'Ahmedabad Junction, GJ',
    to: 'Mumbai Central, MH',
    departureTime: '06:10',
    arrivalTime: '12:45',
    duration: '6h 35m',
    classes: [
      { name: 'Economy', availability: 110, price: 1100 },
      { name: 'Business', availability: 40, price: 2200 },
      { name: 'First', availability: 10, price: 3300 },
    ],
  },
  {
    id: 'T503',
    name: 'Karnavati Express',
    number: '12934',
    from: 'Ahmedabad Junction, GJ',
    to: 'Mumbai Central, MH',
    departureTime: '05:00',
    arrivalTime: '12:25',
    duration: '7h 25m',
    classes: [
        { name: 'Economy', availability: 200, price: 600 },
        { name: 'Business', availability: 50, price: 1300 },
    ],
  },
  // 27. Chennai Central -> Howrah Junction
  {
    id: 'TM1101',
    name: 'Coromandel Express',
    number: '12842',
    from: 'Chennai Central, TN',
    to: 'Howrah Junction, WB',
    departureTime: '07:00',
    arrivalTime: '10:40',
    duration: '27h 40m',
    classes: [
      { name: 'Economy', availability: 220, price: 1000 },
      { name: 'Business', availability: 60, price: 2600 },
    ],
  },
  // 28. Howrah Junction -> Chennai Central
  {
    id: 'TM1102',
    name: 'Coromandel Express',
    number: '12841',
    from: 'Howrah Junction, WB',
    to: 'Chennai Central, TN',
    departureTime: '14:50',
    arrivalTime: '17:00',
    duration: '26h 10m',
    classes: [
      { name: 'Economy', availability: 210, price: 1020 },
      { name: 'Business', availability: 55, price: 2650 },
    ],
  },
  // 29. Chennai Central -> Bengaluru City
  {
    id: 'TM1201',
    name: 'Chennai-Bengaluru Shatabdi',
    number: '12027',
    from: 'Chennai Central, TN',
    to: 'Bengaluru City, KA',
    departureTime: '17:30',
    arrivalTime: '22:25',
    duration: '4h 55m',
    classes: [
      { name: 'Economy', availability: 250, price: 800 },
      { name: 'Business', availability: 50, price: 1500 },
    ],
  },
  {
    id: 'TM1202',
    name: 'Lalbagh Express',
    number: '12607',
    from: 'Chennai Central, TN',
    to: 'Bengaluru City, KA',
    departureTime: '15:30',
    arrivalTime: '21:35',
    duration: '6h 05m',
    classes: [
      { name: 'Economy', availability: 300, price: 450 },
      { name: 'Business', availability: 100, price: 950 },
    ],
  },
  // 30. Bengaluru City -> Chennai Central
  {
    id: 'TM1203',
    name: 'Bengaluru-Chennai Shatabdi',
    number: '12028',
    from: 'Bengaluru City, KA',
    to: 'Chennai Central, TN',
    departureTime: '06:00',
    arrivalTime: '11:00',
    duration: '5h 00m',
    classes: [
      { name: 'Economy', availability: 240, price: 820 },
      { name: 'Business', availability: 45, price: 1550 },
    ],
  },
  {
    id: 'TM1204',
    name: 'Lalbagh Express',
    number: '12608',
    from: 'Bengaluru City, KA',
    to: 'Chennai Central, TN',
    departureTime: '06:20',
    arrivalTime: '12:10',
    duration: '5h 50m',
    classes: [
      { name: 'Economy', availability: 290, price: 470 },
      { name: 'Business', availability: 90, price: 980 },
    ],
  },
  // 31. Chennai Central -> Secunderabad Jn
  {
    id: 'TM1301',
    name: 'Charminar Express',
    number: '12759',
    from: 'Chennai Central, TN',
    to: 'Secunderabad Jn, TS',
    departureTime: '17:45',
    arrivalTime: '06:35',
    duration: '12h 50m',
    classes: [
      { name: 'Economy', availability: 150, price: 650 },
      { name: 'Business', availability: 40, price: 1600 },
    ],
  },
  // 32. Secunderabad Jn -> Chennai Central
  {
    id: 'TM1302',
    name: 'Charminar Express',
    number: '12760',
    from: 'Secunderabad Jn, TS',
    to: 'Chennai Central, TN',
    departureTime: '18:00',
    arrivalTime: '07:00',
    duration: '13h 00m',
    classes: [
      { name: 'Economy', availability: 140, price: 670 },
      { name: 'Business', availability: 35, price: 1650 },
    ],
  },
  // 33. Chennai Central -> Pune Junction
  {
    id: 'TM1401',
    name: 'Chennai-Pune Superfast',
    number: '12164',
    from: 'Chennai Central, TN',
    to: 'Pune Junction, MH',
    departureTime: '06:45',
    arrivalTime: '05:00',
    duration: '22h 15m',
    classes: [
      { name: 'Economy', availability: 100, price: 800 },
      { name: 'Business', availability: 30, price: 2100 },
    ],
  },
  // 34. Pune Junction -> Chennai Central
  {
    id: 'TM1402',
    name: 'Pune-Chennai Superfast',
    number: '12163',
    from: 'Pune Junction, MH',
    to: 'Chennai Central, TN',
    departureTime: '00:10',
    arrivalTime: '20:30',
    duration: '20h 20m',
    classes: [
      { name: 'Economy', availability: 90, price: 820 },
      { name: 'Business', availability: 25, price: 2150 },
    ],
  },
  // 35. Chennai Central -> Ahmedabad Junction
  {
    id: 'TM1501',
    name: 'Navjeevan Express',
    number: '12656',
    from: 'Chennai Central, TN',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '10:10',
    arrivalTime: '18:00',
    duration: '31h 50m',
    classes: [
      { name: 'Economy', availability: 120, price: 1100 },
      { name: 'Business', availability: 40, price: 2800 },
    ],
  },
  // 36. Ahmedabad Junction -> Chennai Central
  {
    id: 'TM1502',
    name: 'Navjeevan Express',
    number: '12655',
    from: 'Ahmedabad Junction, GJ',
    to: 'Chennai Central, TN',
    departureTime: '07:35',
    arrivalTime: '15:25',
    duration: '31h 50m',
    classes: [
      { name: 'Economy', availability: 110, price: 1120 },
      { name: 'Business', availability: 35, price: 2850 },
    ],
  },
  // 37. Howrah Junction -> Bengaluru City
  {
    id: 'TM1601',
    name: 'Duronto Express',
    number: '12245',
    from: 'Howrah Junction, WB',
    to: 'Bengaluru City, KA',
    departureTime: '10:50',
    arrivalTime: '15:50',
    duration: '29h 00m',
    classes: [
      { name: 'Economy', availability: 100, price: 2300 },
      { name: 'Business', availability: 40, price: 3800 },
    ],
  },
  // 38. Bengaluru City -> Howrah Junction
  {
    id: 'TM1602',
    name: 'Duronto Express',
    number: '12246',
    from: 'Bengaluru City, KA',
    to: 'Howrah Junction, WB',
    departureTime: '11:20',
    arrivalTime: '16:40',
    duration: '29h 20m',
    classes: [
      { name: 'Economy', availability: 90, price: 2350 },
      { name: 'Business', availability: 35, price: 3850 },
    ],
  },
  // 39. Howrah Junction -> Secunderabad Jn
  {
    id: 'TM1701',
    name: 'Falaknuma Express',
    number: '12703',
    from: 'Howrah Junction, WB',
    to: 'Secunderabad Jn, TS',
    departureTime: '07:25',
    arrivalTime: '09:35',
    duration: '26h 10m',
    classes: [
      { name: 'Economy', availability: 160, price: 950 },
      { name: 'Business', availability: 50, price: 2500 },
    ],
  },
  // 40. Secunderabad Jn -> Howrah Junction
  {
    id: 'TM1702',
    name: 'Falaknuma Express',
    number: '12704',
    from: 'Secunderabad Jn, TS',
    to: 'Howrah Junction, WB',
    departureTime: '15:55',
    arrivalTime: '17:40',
    duration: '25h 45m',
    classes: [
      { name: 'Economy', availability: 150, price: 970 },
      { name: 'Business', availability: 45, price: 2550 },
    ],
  },
  // 41. Howrah Junction -> Pune Junction
  {
    id: 'TM1801',
    name: 'Azad Hind Express',
    number: '12130',
    from: 'Howrah Junction, WB',
    to: 'Pune Junction, MH',
    departureTime: '21:50',
    arrivalTime: '06:50',
    duration: '33h 00m',
    classes: [
      { name: 'Economy', availability: 110, price: 1150 },
      { name: 'Business', availability: 30, price: 2900 },
    ],
  },
  // 42. Pune Junction -> Howrah Junction
  {
    id: 'TM1802',
    name: 'Azad Hind Express',
    number: '12129',
    from: 'Pune Junction, MH',
    to: 'Howrah Junction, WB',
    departureTime: '18:25',
    arrivalTime: '03:55',
    duration: '33h 30m',
    classes: [
      { name: 'Economy', availability: 100, price: 1170 },
      { name: 'Business', availability: 25, price: 2950 },
    ],
  },
  // 43. Howrah Junction -> Ahmedabad Junction
  {
    id: 'TM1901',
    name: 'Howrah-Ahmedabad Superfast',
    number: '12834',
    from: 'Howrah Junction, WB',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '23:55',
    arrivalTime: '12:05',
    duration: '36h 10m',
    classes: [
      { name: 'Economy', availability: 130, price: 1200 },
      { name: 'Business', availability: 40, price: 3100 },
    ],
  },
  // 44. Ahmedabad Junction -> Howrah Junction
  {
    id: 'TM1902',
    name: 'Ahmedabad-Howrah Superfast',
    number: '12833',
    from: 'Ahmedabad Junction, GJ',
    to: 'Howrah Junction, WB',
    departureTime: '00:25',
    arrivalTime: '13:30',
    duration: '37h 05m',
    classes: [
      { name: 'Economy', availability: 120, price: 1220 },
      { name: 'Business', availability: 35, price: 3150 },
    ],
  },
  // 45. Bengaluru City -> Secunderabad Jn
  {
    id: 'TM2001',
    name: 'Garibrath Express',
    number: '12736',
    from: 'Bengaluru City, KA',
    to: 'Secunderabad Jn, TS',
    departureTime: '16:15',
    arrivalTime: '04:00',
    duration: '11h 45m',
    classes: [
      { name: 'Economy', availability: 200, price: 600 },
      { name: 'Business', availability: 70, price: 1400 },
    ],
  },
  // 46. Secunderabad Jn -> Bengaluru City
  {
    id: 'TM2002',
    name: 'Garibrath Express',
    number: '12735',
    from: 'Secunderabad Jn, TS',
    to: 'Bengaluru City, KA',
    departureTime: '20:30',
    arrivalTime: '08:20',
    duration: '11h 50m',
    classes: [
      { name: 'Economy', availability: 190, price: 620 },
      { name: 'Business', availability: 65, price: 1450 },
    ],
  },
  // 47. Bengaluru City -> Pune Junction
  {
    id: 'TM2101',
    name: 'Chalukya Express',
    number: '11018',
    from: 'Bengaluru City, KA',
    to: 'Pune Junction, MH',
    departureTime: '15:45',
    arrivalTime: '17:30',
    duration: '25h 45m',
    classes: [
      { name: 'Economy', availability: 90, price: 750 },
      { name: 'Business', availability: 20, price: 1900 },
    ],
  },
  // 48. Pune Junction -> Bengaluru City
  {
    id: 'TM2102',
    name: 'Chalukya Express',
    number: '11017',
    from: 'Pune Junction, MH',
    to: 'Bengaluru City, KA',
    departureTime: '01:05',
    arrivalTime: '04:40',
    duration: '27h 35m',
    classes: [
      { name: 'Economy', availability: 80, price: 770 },
      { name: 'Business', availability: 15, price: 1950 },
    ],
  },
  // 49. Bengaluru City -> Ahmedabad Junction
  {
    id: 'TM2201',
    name: 'Jodhpur Express',
    number: '16508',
    from: 'Bengaluru City, KA',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '22:20',
    arrivalTime: '08:45',
    duration: '34h 25m',
    classes: [
      { name: 'Economy', availability: 80, price: 1150 },
      { name: 'Business', availability: 25, price: 2900 },
    ],
  },
  // 50. Ahmedabad Junction -> Bengaluru City
  {
    id: 'TM2202',
    name: 'Jodhpur Express',
    number: '16507',
    from: 'Ahmedabad Junction, GJ',
    to: 'Bengaluru City, KA',
    departureTime: '17:45',
    arrivalTime: '03:45',
    duration: '34h 00m',
    classes: [
      { name: 'Economy', availability: 70, price: 1170 },
      { name: 'Business', availability: 20, price: 2950 },
    ],
  },
  // 51. Secunderabad Jn -> Pune Junction
  {
    id: 'T501R',
    name: 'Secunderabad-Pune Shatabdi',
    number: '12026',
    from: 'Secunderabad Jn, TS',
    to: 'Pune Junction, MH',
    departureTime: '14:45',
    arrivalTime: '23:10',
    duration: '8h 25m',
    classes: [
      { name: 'Economy', availability: 85, price: 1250 },
      { name: 'Business', availability: 25, price: 2050 },
      { name: 'First', availability: 5, price: 3050 },
    ],
  },
  // 52. Pune Junction -> Secunderabad Jn
  {
    id: 'T501',
    name: 'Pune-Secunderabad Shatabdi',
    number: '12025',
    from: 'Pune Junction, MH',
    to: 'Secunderabad Jn, TS',
    departureTime: '06:00',
    arrivalTime: '14:20',
    duration: '8h 20m',
    classes: [
      { name: 'Economy', availability: 90, price: 1200 },
      { name: 'Business', availability: 30, price: 2000 },
    ],
  },
  // 53. Secunderabad Jn -> Ahmedabad Junction
  {
    id: 'TM2301',
    name: 'Secunderabad-Rajkot Express',
    number: '17018',
    from: 'Secunderabad Jn, TS',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '15:15',
    arrivalTime: '16:00',
    duration: '24h 45m',
    classes: [
      { name: 'Economy', availability: 90, price: 850 },
      { name: 'Business', availability: 20, price: 2200 },
    ],
  },
  // 54. Ahmedabad Junction -> Secunderabad Jn
  {
    id: 'TM2302',
    name: 'Rajkot-Secunderabad Express',
    number: '17017',
    from: 'Ahmedabad Junction, GJ',
    to: 'Secunderabad Jn, TS',
    departureTime: '09:20',
    arrivalTime: '10:30',
    duration: '25h 10m',
    classes: [
      { name: 'Economy', availability: 80, price: 870 },
      { name: 'Business', availability: 15, price: 2250 },
    ],
  },
  // 55. Pune Junction -> Ahmedabad Junction
  {
    id: 'TM2401',
    name: 'Pune-Ahmedabad Duronto',
    number: '12298',
    from: 'Pune Junction, MH',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '21:35',
    arrivalTime: '06:25',
    duration: '8h 50m',
    classes: [
      { name: 'Economy', availability: 130, price: 1300 },
      { name: 'Business', availability: 40, price: 2400 },
    ],
  },
  // 56. Ahmedabad Junction -> Pune Junction
  {
    id: 'TM2402',
    name: 'Ahmedabad-Pune Duronto',
    number: '12297',
    from: 'Ahmedabad Junction, GJ',
    to: 'Pune Junction, MH',
    departureTime: '22:30',
    arrivalTime: '07:15',
    duration: '8h 45m',
    classes: [
      { name: 'Economy', availability: 120, price: 1320 },
      { name: 'Business', availability: 35, price: 2450 },
    ],
  },
];


// In a real application, this would be a database call.
// For this prototype, we'll just modify the in-memory array.
export function updateTrainAvailability(trainId: string, className: 'Economy' | 'Business' | 'First', passengers: number) {
    const train = trains.find(t => t.id === trainId);
    if (!train) return false;

    const trainClass = train.classes.find(c => c.name === className);
    if (!trainClass) return false;

    if (trainClass.availability < passengers) return false;

    trainClass.availability -= passengers;
    return true;
}
