import type { Train, User, Booking } from './types';

export const stations = [
  'New Delhi, DL',
  'Mumbai Central, MH',
  'Chennai Central, TN',
  'Howrah Junction, WB',
  'Bengaluru City, KA',
  'Secunderabad Jn, TS',
  'Pune Junction, MH',
  'Ahmedabad Junction, GJ',
];

export const trains: Train[] = [
  // 1. New Delhi <=> Mumbai Central
  {
    id: 'TM101',
    name: 'Delhi-Mumbai Rajdhani',
    number: '12952',
    from: 'New Delhi, DL',
    to: 'Mumbai Central, MH',
    departureTime: '16:55',
    arrivalTime: '08:15',
    duration: '15h 20m',
    classes: [
      { name: '1AC', availability: 8, price: 5450 },
      { name: '2AC', availability: 35, price: 3550 },
      { name: '3AC', availability: 145, price: 2150 },
    ],
  },
  {
    id: 'TM102',
    name: 'Delhi-Mumbai Duronto',
    number: '22210',
    from: 'New Delhi, DL',
    to: 'Mumbai Central, MH',
    departureTime: '23:25',
    arrivalTime: '15:50',
    duration: '16h 25m',
    classes: [
      { name: '1AC', availability: 12, price: 4800 },
      { name: '2AC', availability: 50, price: 3300 },
      { name: '3AC', availability: 210, price: 1950 },
      { name: 'Sleeper', availability: 400, price: 850 },
    ],
  },
  {
    id: 'T123',
    name: 'Mumbai-Delhi Rajdhani',
    number: '12951',
    from: 'Mumbai Central, MH',
    to: 'New Delhi, DL',
    departureTime: '17:00',
    arrivalTime: '08:30',
    duration: '15h 30m',
    classes: [
      { name: '1AC', availability: 10, price: 5400 },
      { name: '2AC', availability: 40, price: 3500 },
      { name: '3AC', availability: 150, price: 2100 },
    ],
  },
  {
    id: 'T124',
    name: 'August Kranti Rajdhani',
    number: '12953',
    from: 'Mumbai Central, MH',
    to: 'New Delhi, DL',
    departureTime: '17:10',
    arrivalTime: '10:55',
    duration: '17h 45m',
    classes: [
      { name: '1AC', availability: 5, price: 5200 },
      { name: '2AC', availability: 30, price: 3300 },
      { name: '3AC', availability: 120, price: 2000 },
      { name: 'Sleeper', availability: 350, price: 800 },
    ],
  },
   // 2. New Delhi <=> Chennai Central
  {
    id: 'TM201',
    name: 'Tamil Nadu Express',
    number: '12622',
    from: 'New Delhi, DL',
    to: 'Chennai Central, TN',
    departureTime: '21:05',
    arrivalTime: '06:15',
    duration: '33h 10m',
    classes: [
        { name: '1AC', availability: 20, price: 4800 },
        { name: '2AC', availability: 70, price: 2800 },
        { name: '3AC', availability: 150, price: 1800 },
        { name: 'Sleeper', availability: 250, price: 1100 },
    ],
  },
  {
    id: 'TM202',
    name: 'Delhi-Chennai Rajdhani',
    number: '12434',
    from: 'New Delhi, DL',
    to: 'Chennai Central, TN',
    departureTime: '15:35',
    arrivalTime: '20:45',
    duration: '29h 10m',
    classes: [
        { name: '1AC', availability: 18, price: 6300 },
        { name: '2AC', availability: 60, price: 4100 },
        { name: '3AC', availability: 180, price: 2500 },
    ],
  },
  {
    id: 'T601',
    name: 'Grand Trunk Express',
    number: '12615',
    from: 'Chennai Central, TN',
    to: 'New Delhi, DL',
    departureTime: '18:50',
    arrivalTime: '05:05',
    duration: '34h 15m',
    classes: [
        { name: '1AC', availability: 20, price: 4500 },
        { name: '2AC', availability: 80, price: 2500 },
        { name: '3AC', availability: 180, price: 1500 },
        { name: 'Sleeper', availability: 250, price: 1000 },
    ],
  },
  {
    id: 'T212',
    name: 'Chennai-Delhi Rajdhani',
    number: '12433',
    from: 'Chennai Central, TN',
    to: 'New Delhi, DL',
    departureTime: '06:05',
    arrivalTime: '10:30',
    duration: '28h 25m',
    classes: [
      { name: '1AC', availability: 15, price: 6200 },
      { name: '2AC', availability: 60, price: 4000 },
      { name: '3AC', availability: 0, price: 2400 },
    ],
  },
  // 3. New Delhi <=> Howrah Junction
  {
    id: 'T789R',
    name: 'Delhi-Howrah Rajdhani',
    number: '12302',
    from: 'New Delhi, DL',
    to: 'Howrah Junction, WB',
    departureTime: '16:55',
    arrivalTime: '09:55',
    duration: '17h 00m',
    classes: [
        { name: '1AC', availability: 10, price: 5850 },
        { name: '2AC', availability: 20, price: 3850 },
        { name: '3AC', availability: 110, price: 2250 },
    ],
  },
  {
    id: 'T790R',
    name: 'Poorva Express',
    number: '12304',
    from: 'New Delhi, DL',
    to: 'Howrah Junction, WB',
    departureTime: '17:40',
    arrivalTime: '17:00',
    duration: '23h 20m',
    classes: [
      { name: '1AC', availability: 25, price: 2850 },
      { name: '2AC', availability: 90, price: 1550 },
      { name: 'Sleeper', availability: 280, price: 870 },
    ],
  },
  {
    id: 'T789',
    name: 'Howrah-Delhi Rajdhani',
    number: '12301',
    from: 'Howrah Junction, WB',
    to: 'New Delhi, DL',
    departureTime: '16:50',
    arrivalTime: '10:00',
    duration: '17h 10m',
    classes: [
      { name: '1AC', availability: 8, price: 5800 },
      { name: '2AC', availability: 25, price: 3800 },
      { name: '3AC', availability: 105, price: 2200 },
    ],
  },
  {
    id: 'T790',
    name: 'Poorva Express',
    number: '12303',
    from: 'Howrah Junction, WB',
    to: 'New Delhi, DL',
    departureTime: '08:00',
    arrivalTime: '06:00',
    duration: '22h 00m',
    classes: [
      { name: '1AC', availability: 30, price: 2800 },
      { name: '2AC', availability: 100, price: 1500 },
      { name: 'Sleeper', availability: 300, price: 850 },
    ],
  },
  // 4. New Delhi <=> Bengaluru City
  {
    id: 'T456R',
    name: 'Delhi-Bengaluru Rajdhani',
    number: '22692',
    from: 'New Delhi, DL',
    to: 'Bengaluru City, KA',
    departureTime: '20:45',
    arrivalTime: '06:40',
    duration: '33h 55m',
    classes: [
        { name: '1AC', availability: 12, price: 6050 },
        { name: '2AC', availability: 45, price: 4250 },
        { name: '3AC', availability: 180, price: 2550 },
    ],
  },
  {
    id: 'T457R',
    name: 'Karnataka Express',
    number: '12628',
    from: 'New Delhi, DL',
    to: 'Bengaluru City, KA',
    departureTime: '20:20',
    arrivalTime: '13:40',
    duration: '41h 20m',
    classes: [
      { name: '1AC', availability: 3, price: 3450 },
      { name: '2AC', availability: 8, price: 1950 },
      { name: '3AC Eco', availability: 50, price: 1250 },
      { name: 'Sleeper', availability: 115, price: 980 },
    ],
  },
  {
    id: 'T456',
    name: 'Bengaluru-Delhi Rajdhani',
    number: '22691',
    from: 'Bengaluru City, KA',
    to: 'New Delhi, DL',
    departureTime: '20:00',
    arrivalTime: '05:30',
    duration: '33h 30m',
    classes: [
      { name: '1AC', availability: 0, price: 6000 },
      { name: '2AC', availability: 50, price: 4200 },
      { name: '3AC', availability: 200, price: 2500 },
    ],
  },
  {
    id: 'T457',
    name: 'Karnataka Express',
    number: '12627',
    from: 'Bengaluru City, KA',
    to: 'New Delhi, DL',
    departureTime: '19:20',
    arrivalTime: '09:00',
    duration: '37h 40m',
    classes: [
      { name: '1AC', availability: 2, price: 3400 },
      { name: '2AC', availability: 5, price: 1900 },
      { name: '3AC Eco', availability: 40, price: 1200 },
      { name: 'Sleeper', availability: 110, price: 950 },
    ],
  },
  // 5. New Delhi <=> Secunderabad Jn
  {
    id: 'T101R',
    name: 'Delhi-Secunderabad Duronto',
    number: '12286',
    from: 'New Delhi, DL',
    to: 'Secunderabad Jn, TS',
    departureTime: '15:55',
    arrivalTime: '14:50',
    duration: '22h 55m',
    classes: [
      { name: '1AC', availability: 4, price: 5050 },
      { name: '2AC', availability: 15, price: 3250 },
      { name: '3AC', availability: 70, price: 1850 },
    ],
  },
  {
    id: 'TM301',
    name: 'Telangana Express',
    number: '12724',
    from: 'New Delhi, DL',
    to: 'Secunderabad Jn, TS',
    departureTime: '17:25',
    arrivalTime: '19:30',
    duration: '26h 05m',
    classes: [
      { name: '2AC', availability: 60, price: 2400 },
      { name: '3AC Eco', availability: 150, price: 1400 },
      { name: 'Sleeper', availability: 200, price: 900 },
    ],
  },
  {
    id: 'T101',
    name: 'Secunderabad-Delhi Duronto',
    number: '12285',
    from: 'Secunderabad Jn, TS',
    to: 'New Delhi, DL',
    departureTime: '12:50',
    arrivalTime: '10:35',
    duration: '21h 45m',
    classes: [
      { name: '1AC', availability: 5, price: 5000 },
      { name: '2AC', availability: 20, price: 3200 },
      { name: '3AC', availability: 80, price: 1800 },
    ],
  },
  {
    id: 'TM302',
    name: 'Telangana Express',
    number: '12723',
    from: 'Secunderabad Jn, TS',
    to: 'New Delhi, DL',
    departureTime: '06:25',
    arrivalTime: '09:05',
    duration: '26h 40m',
    classes: [
      { name: '2AC', availability: 55, price: 2450 },
      { name: '3AC Eco', availability: 140, price: 1420 },
      { name: 'Sleeper', availability: 220, price: 920 },
    ],
  },
  // 6. New Delhi <=> Pune Junction
  {
    id: 'TM401',
    name: 'Delhi-Pune Duronto',
    number: '12264',
    from: 'New Delhi, DL',
    to: 'Pune Junction, MH',
    departureTime: '10:55',
    arrivalTime: '07:10',
    duration: '20h 15m',
    classes: [
      { name: '1AC', availability: 10, price: 4500 },
      { name: '2AC', availability: 30, price: 3000 },
      { name: '3AC', availability: 100, price: 1700 },
    ],
  },
  {
    id: 'TM402',
    name: 'Goa Express',
    number: '12780',
    from: 'New Delhi, DL',
    to: 'Pune Junction, MH',
    departureTime: '15:00',
    arrivalTime: '22:20',
    duration: '31h 20m',
    classes: [
      { name: '2AC', availability: 40, price: 2500 },
      { name: '3AC', availability: 100, price: 1500 },
      { name: 'Sleeper', availability: 150, price: 950 },
    ],
  },
  {
    id: 'TM403',
    name: 'Pune-Delhi Duronto',
    number: '12263',
    from: 'Pune Junction, MH',
    to: 'New Delhi, DL',
    departureTime: '11:10',
    arrivalTime: '06:45',
    duration: '19h 35m',
    classes: [
      { name: '1AC', availability: 8, price: 4550 },
      { name: '2AC', availability: 25, price: 3050 },
      { name: '3AC', availability: 90, price: 1750 },
    ],
  },
  {
    id: 'TM404',
    name: 'Goa Express (Return)',
    number: '12779',
    from: 'Pune Junction, MH',
    to: 'New Delhi, DL',
    departureTime: '04:20',
    arrivalTime: '15:00',
    duration: '34h 40m',
    classes: [
      { name: '2AC', availability: 45, price: 2550 },
      { name: '3AC', availability: 110, price: 1550 },
      { name: 'Sleeper', availability: 160, price: 960 },
    ],
  },
  // 7. New Delhi <=> Ahmedabad Junction
  {
    id: 'TM501',
    name: 'Ashram Express',
    number: '12916',
    from: 'New Delhi, DL',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '14:55',
    arrivalTime: '06:20',
    duration: '15h 25m',
    classes: [
      { name: '2AC', availability: 80, price: 1800 },
      { name: '3AC', availability: 150, price: 1200 },
      { name: 'Sleeper', availability: 300, price: 750 },
    ],
  },
  {
    id: 'TM501B',
    name: 'Delhi-Ahmedabad Rajdhani',
    number: '12958',
    from: 'New Delhi, DL',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '19:55',
    arrivalTime: '09:40',
    duration: '13h 45m',
    classes: [
      { name: '1AC', availability: 20, price: 3200 },
      { name: '2AC', availability: 50, price: 2800 },
      { name: '3AC', availability: 120, price: 1500 },
    ],
  },
  {
    id: 'TM502',
    name: 'Ashram Express',
    number: '12915',
    from: 'Ahmedabad Junction, GJ',
    to: 'New Delhi, DL',
    departureTime: '19:15',
    arrivalTime: '10:00',
    duration: '14h 45m',
    classes: [
      { name: '2AC', availability: 70, price: 1820 },
      { name: '3AC', availability: 140, price: 1220 },
      { name: 'Sleeper', availability: 280, price: 760 },
    ],
  },
  {
    id: 'TM502B',
    name: 'Ahmedabad-Delhi Rajdhani',
    number: '12957',
    from: 'Ahmedabad Junction, GJ',
    to: 'New Delhi, DL',
    departureTime: '18:50',
    arrivalTime: '07:30',
    duration: '12h 40m',
    classes: [
      { name: '1AC', availability: 18, price: 3250 },
      { name: '2AC', availability: 45, price: 2850 },
      { name: '3AC', availability: 110, price: 1550 },
    ],
  },
  // 8. Mumbai Central <=> Chennai Central
  {
    id: 'TM601',
    name: 'Mumbai-Chennai Express',
    number: '22159',
    from: 'Mumbai Central, MH',
    to: 'Chennai Central, TN',
    departureTime: '12:45',
    arrivalTime: '10:45',
    duration: '22h 00m',
    classes: [
      { name: '2AC', availability: 60, price: 2300 },
      { name: '3AC', availability: 120, price: 1600 },
      { name: 'Sleeper', availability: 200, price: 900 },
    ],
  },
  {
    id: 'TM601B',
    name: 'Mumbai-Chennai Mail',
    number: '11027',
    from: 'Mumbai Central, MH',
    to: 'Chennai Central, TN',
    departureTime: '23:45',
    arrivalTime: '04:15',
    duration: '28h 30m',
    classes: [
      { name: '2AC', availability: 65, price: 2320 },
      { name: '3AC', availability: 130, price: 1620 },
      { name: 'Sleeper', availability: 210, price: 910 },
    ],
  },
  {
    id: 'TM602',
    name: 'Chennai-Mumbai Express',
    number: '22160',
    from: 'Chennai Central, TN',
    to: 'Mumbai Central, MH',
    departureTime: '13:15',
    arrivalTime: '12:00',
    duration: '22h 45m',
    classes: [
      { name: '2AC', availability: 50, price: 2350 },
      { name: '3AC', availability: 110, price: 1650 },
      { name: 'Sleeper', availability: 180, price: 920 },
    ],
  },
  {
    id: 'TM602B',
    name: 'Chennai-Mumbai Mail',
    number: '11028',
    from: 'Chennai Central, TN',
    to: 'Mumbai Central, MH',
    departureTime: '23:55',
    arrivalTime: '05:40',
    duration: '29h 45m',
    classes: [
      { name: '2AC', availability: 55, price: 2380 },
      { name: '3AC', availability: 120, price: 1680 },
      { name: 'Sleeper', availability: 190, price: 930 },
    ],
  },
  // 9. Mumbai Central <=> Howrah Junction
  {
    id: 'TM701',
    name: 'Mumbai-Howrah Mail',
    number: '12322',
    from: 'Mumbai Central, MH',
    to: 'Howrah Junction, WB',
    departureTime: '22:15',
    arrivalTime: '11:40',
    duration: '37h 25m',
    classes: [
      { name: '2AC', availability: 40, price: 3000 },
      { name: '3AC', availability: 100, price: 2000 },
      { name: 'Sleeper', availability: 150, price: 1200 },
    ],
  },
  {
    id: 'TM701B',
    name: 'Gitanjali Express',
    number: '12859',
    from: 'Mumbai Central, MH',
    to: 'Howrah Junction, WB',
    departureTime: '06:00',
    arrivalTime: '12:30',
    duration: '30h 30m',
    classes: [
      { name: '2AC', availability: 45, price: 3020 },
      { name: '3AC', availability: 110, price: 2020 },
      { name: 'Sleeper', availability: 160, price: 1210 },
    ],
  },
  {
    id: 'TM702',
    name: 'Howrah-Mumbai Mail',
    number: '12321',
    from: 'Howrah Junction, WB',
    to: 'Mumbai Central, MH',
    departureTime: '22:00',
    arrivalTime: '13:15',
    duration: '39h 15m',
    classes: [
      { name: '2AC', availability: 35, price: 3050 },
      { name: '3AC', availability: 90, price: 2050 },
      { name: 'Sleeper', availability: 140, price: 1250 },
    ],
  },
  {
    id: 'TM702B',
    name: 'Gitanjali Express',
    number: '12860',
    from: 'Howrah Junction, WB',
    to: 'Mumbai Central, MH',
    departureTime: '13:50',
    arrivalTime: '21:20',
    duration: '31h 30m',
    classes: [
      { name: '2AC', availability: 40, price: 3080 },
      { name: '3AC', availability: 100, price: 2080 },
      { name: 'Sleeper', availability: 145, price: 1260 },
    ],
  },
  // 10. Mumbai Central <=> Bengaluru City
  {
    id: 'TM801',
    name: 'Udyan Express',
    number: '11301',
    from: 'Mumbai Central, MH',
    to: 'Bengaluru City, KA',
    departureTime: '08:10',
    arrivalTime: '08:50',
    duration: '24h 40m',
    classes: [
      { name: '2AC', availability: 50, price: 2200 },
      { name: '3AC', availability: 120, price: 1500 },
      { name: 'Sleeper', availability: 180, price: 850 },
    ],
  },
  {
    id: 'TM801B',
    name: 'Coimbatore Express',
    number: '11013',
    from: 'Mumbai Central, MH',
    to: 'Bengaluru City, KA',
    departureTime: '22:35',
    arrivalTime: '21:30',
    duration: '22h 55m',
    classes: [
      { name: '2AC', availability: 45, price: 2220 },
      { name: '3AC', availability: 110, price: 1520 },
      { name: 'Sleeper', availability: 170, price: 860 },
    ],
  },
  {
    id: 'TM802',
    name: 'Udyan Express',
    number: '11302',
    from: 'Bengaluru City, KA',
    to: 'Mumbai Central, MH',
    departureTime: '20:30',
    arrivalTime: '19:45',
    duration: '23h 15m',
    classes: [
      { name: '2AC', availability: 45, price: 2250 },
      { name: '3AC', availability: 110, price: 1550 },
      { name: 'Sleeper', availability: 170, price: 860 },
    ],
  },
  {
    id: 'TM802B',
    name: 'Coimbatore Express (Return)',
    number: '11014',
    from: 'Bengaluru City, KA',
    to: 'Mumbai Central, MH',
    departureTime: '15:15',
    arrivalTime: '14:30',
    duration: '23h 15m',
    classes: [
      { name: '2AC', availability: 50, price: 2280 },
      { name: '3AC', availability: 120, price: 1580 },
      { name: 'Sleeper', availability: 180, price: 870 },
    ],
  },
  // 11. Mumbai Central <=> Secunderabad Jn
  {
    id: 'TM901',
    name: 'Devagiri Express',
    number: '17057',
    from: 'Mumbai Central, MH',
    to: 'Secunderabad Jn, TS',
    departureTime: '21:30',
    arrivalTime: '14:45',
    duration: '17h 15m',
    classes: [
      { name: '2AC', availability: 30, price: 1800 },
      { name: '3AC', availability: 80, price: 1200 },
      { name: 'Sleeper', availability: 120, price: 700 },
    ],
  },
  {
    id: 'TM901B',
    name: 'Hussain Sagar Express',
    number: '12701',
    from: 'Mumbai Central, MH',
    to: 'Secunderabad Jn, TS',
    departureTime: '21:50',
    arrivalTime: '12:05',
    duration: '14h 15m',
    classes: [
      { name: '2AC', availability: 35, price: 1850 },
      { name: '3AC', availability: 90, price: 1250 },
      { name: 'Sleeper', availability: 130, price: 720 },
    ],
  },
  {
    id: 'TM902',
    name: 'Devagiri Express',
    number: '17058',
    from: 'Secunderabad Jn, TS',
    to: 'Mumbai Central, MH',
    departureTime: '13:25',
    arrivalTime: '07:10',
    duration: '17h 45m',
    classes: [
      { name: '2AC', availability: 25, price: 1850 },
      { name: '3AC', availability: 70, price: 1250 },
      { name: 'Sleeper', availability: 110, price: 720 },
    ],
  },
  {
    id: 'TM902B',
    name: 'Hussain Sagar Express (Return)',
    number: '12702',
    from: 'Secunderabad Jn, TS',
    to: 'Mumbai Central, MH',
    departureTime: '14:50',
    arrivalTime: '05:00',
    duration: '14h 10m',
    classes: [
      { name: '2AC', availability: 30, price: 1880 },
      { name: '3AC', availability: 80, price: 1280 },
      { name: 'Sleeper', availability: 115, price: 730 },
    ],
  },
  // 12. Mumbai Central <=> Pune Junction
  {
    id: 'TM1001',
    name: 'Indrayani Express',
    number: '22105',
    from: 'Mumbai Central, MH',
    to: 'Pune Junction, MH',
    departureTime: '05:40',
    arrivalTime: '09:05',
    duration: '3h 25m',
    classes: [
      { name: '2AC', availability: 80, price: 900 },
      { name: 'Sleeper', availability: 400, price: 450 },
    ],
  },
  {
    id: 'TM1002',
    name: 'Deccan Queen',
    number: '12123',
    from: 'Mumbai Central, MH',
    to: 'Pune Junction, MH',
    departureTime: '17:10',
    arrivalTime: '20:25',
    duration: '3h 15m',
    classes: [
      { name: '1AC', availability: 20, price: 1200 },
      { name: '2AC', availability: 70, price: 1000 },
      { name: 'Sleeper', availability: 350, price: 500 },
    ],
  },
  {
    id: 'TM1003',
    name: 'Indrayani Express',
    number: '22106',
    from: 'Pune Junction, MH',
    to: 'Mumbai Central, MH',
    departureTime: '18:35',
    arrivalTime: '22:00',
    duration: '3h 25m',
    classes: [
      { name: '2AC', availability: 75, price: 920 },
      { name: 'Sleeper', availability: 380, price: 460 },
    ],
  },
  {
    id: 'TM1004',
    name: 'Deccan Queen',
    number: '12124',
    from: 'Pune Junction, MH',
    to: 'Mumbai Central, MH',
    departureTime: '07:15',
    arrivalTime: '10:25',
    duration: '3h 10m',
    classes: [
      { name: '1AC', availability: 25, price: 1220 },
      { name: '2AC', availability: 65, price: 1020 },
      { name: 'Sleeper', availability: 340, price: 510 },
    ],
  },
  // 13. Mumbai Central <=> Ahmedabad Junction
  {
    id: 'T502R',
    name: 'Mumbai-Ahmedabad Shatabdi',
    number: '12010',
    from: 'Mumbai Central, MH',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '17:30',
    arrivalTime: '23:55',
    duration: '6h 25m',
    classes: [
        { name: '1AC', availability: 8, price: 3350 },
        { name: '2AC', availability: 35, price: 2250 },
        { name: '3AC', availability: 100, price: 1150 },
    ],
  },
  {
    id: 'T503R',
    name: 'Karnavati Express',
    number: '12933',
    from: 'Mumbai Central, MH',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '14:05',
    arrivalTime: '21:05',
    duration: '7h 00m',
    classes: [
        { name: '2AC', availability: 45, price: 1350 },
        { name: 'Sleeper', availability: 190, price: 620 },
    ],
  },
  {
    id: 'T502',
    name: 'Ahmedabad-Mumbai Shatabdi',
    number: '12009',
    from: 'Ahmedabad Junction, GJ',
    to: 'Mumbai Central, MH',
    departureTime: '06:10',
    arrivalTime: '12:45',
    duration: '6h 35m',
    classes: [
      { name: '1AC', availability: 10, price: 3300 },
      { name: '2AC', availability: 40, price: 2200 },
      { name: '3AC', availability: 110, price: 1100 },
    ],
  },
  {
    id: 'T503',
    name: 'Karnavati Express',
    number: '12934',
    from: 'Ahmedabad Junction, GJ',
    to: 'Mumbai Central, MH',
    departureTime: '05:00',
    arrivalTime: '12:25',
    duration: '7h 25m',
    classes: [
        { name: '2AC', availability: 50, price: 1300 },
        { name: 'Sleeper', availability: 200, price: 600 },
    ],
  },
  // 14. Chennai Central <=> Howrah Junction
  {
    id: 'TM1101',
    name: 'Coromandel Express',
    number: '12842',
    from: 'Chennai Central, TN',
    to: 'Howrah Junction, WB',
    departureTime: '07:00',
    arrivalTime: '10:40',
    duration: '27h 40m',
    classes: [
      { name: '2AC', availability: 60, price: 2600 },
      { name: '3AC', availability: 120, price: 1800 },
      { name: 'Sleeper', availability: 220, price: 1000 },
    ],
  },
  {
    id: 'TM1101B',
    name: 'Chennai-Howrah Mail',
    number: '12840',
    from: 'Chennai Central, TN',
    to: 'Howrah Junction, WB',
    departureTime: '23:45',
    arrivalTime: '04:10',
    duration: '28h 25m',
    classes: [
      { name: '2AC', availability: 65, price: 2620 },
      { name: '3AC', availability: 130, price: 1820 },
      { name: 'Sleeper', availability: 230, price: 1010 },
    ],
  },
  {
    id: 'TM1102',
    name: 'Coromandel Express',
    number: '12841',
    from: 'Howrah Junction, WB',
    to: 'Chennai Central, TN',
    departureTime: '14:50',
    arrivalTime: '17:00',
    duration: '26h 10m',
    classes: [
      { name: '2AC', availability: 55, price: 2650 },
      { name: '3AC', availability: 110, price: 1850 },
      { name: 'Sleeper', availability: 210, price: 1020 },
    ],
  },
  {
    id: 'TM1102B',
    name: 'Howrah-Chennai Mail',
    number: '12839',
    from: 'Howrah Junction, WB',
    to: 'Chennai Central, TN',
    departureTime: '23:55',
    arrivalTime: '03:50',
    duration: '27h 55m',
    classes: [
      { name: '2AC', availability: 60, price: 2680 },
      { name: '3AC', availability: 120, price: 1880 },
      { name: 'Sleeper', availability: 215, price: 1030 },
    ],
  },
  // 15. Chennai Central <=> Bengaluru City
  {
    id: 'TM1201',
    name: 'Chennai-Bengaluru Shatabdi',
    number: '12027',
    from: 'Chennai Central, TN',
    to: 'Bengaluru City, KA',
    departureTime: '17:30',
    arrivalTime: '22:25',
    duration: '4h 55m',
    classes: [
      { name: '1AC', availability: 20, price: 1800 },
      { name: '2AC', availability: 50, price: 1500 },
      { name: '3AC', availability: 250, price: 800 },
    ],
  },
  {
    id: 'TM1202',
    name: 'Lalbagh Express',
    number: '12607',
    from: 'Chennai Central, TN',
    to: 'Bengaluru City, KA',
    departureTime: '15:30',
    arrivalTime: '21:35',
    duration: '6h 05m',
    classes: [
      { name: '2AC', availability: 100, price: 950 },
      { name: '3AC Eco', availability: 200, price: 650 },
      { name: 'Sleeper', availability: 300, price: 450 },
    ],
  },
  {
    id: 'TM1203',
    name: 'Bengaluru-Chennai Shatabdi',
    number: '12028',
    from: 'Bengaluru City, KA',
    to: 'Chennai Central, TN',
    departureTime: '06:00',
    arrivalTime: '11:00',
    duration: '5h 00m',
    classes: [
      { name: '1AC', availability: 18, price: 1850 },
      { name: '2AC', availability: 45, price: 1550 },
      { name: '3AC', availability: 240, price: 820 },
    ],
  },
  {
    id: 'TM1204',
    name: 'Lalbagh Express',
    number: '12608',
    from: 'Bengaluru City, KA',
    to: 'Chennai Central, TN',
    departureTime: '06:20',
    arrivalTime: '12:10',
    duration: '5h 50m',
    classes: [
      { name: '2AC', availability: 90, price: 980 },
      { name: '3AC Eco', availability: 180, price: 680 },
      { name: 'Sleeper', availability: 290, price: 470 },
    ],
  },
  // 16. Chennai Central <=> Secunderabad Jn
  {
    id: 'TM1301',
    name: 'Charminar Express',
    number: '12759',
    from: 'Chennai Central, TN',
    to: 'Secunderabad Jn, TS',
    departureTime: '17:45',
    arrivalTime: '06:35',
    duration: '12h 50m',
    classes: [
      { name: '2AC', availability: 40, price: 1600 },
      { name: '3AC', availability: 100, price: 1100 },
      { name: 'Sleeper', availability: 150, price: 650 },
    ],
  },
  {
    id: 'TM1301B',
    name: 'Hyderabad Express',
    number: '12603',
    from: 'Chennai Central, TN',
    to: 'Secunderabad Jn, TS',
    departureTime: '16:45',
    arrivalTime: '05:45',
    duration: '13h 00m',
    classes: [
      { name: '2AC', availability: 45, price: 1620 },
      { name: '3AC', availability: 110, price: 1120 },
      { name: 'Sleeper', availability: 160, price: 660 },
    ],
  },
  {
    id: 'TM1302',
    name: 'Charminar Express',
    number: '12760',
    from: 'Secunderabad Jn, TS',
    to: 'Chennai Central, TN',
    departureTime: '18:00',
    arrivalTime: '07:00',
    duration: '13h 00m',
    classes: [
      { name: '2AC', availability: 35, price: 1650 },
      { name: '3AC', availability: 90, price: 1150 },
      { name: 'Sleeper', availability: 140, price: 670 },
    ],
  },
  {
    id: 'TM1302B',
    name: 'Hyderabad Express (Return)',
    number: '12604',
    from: 'Secunderabad Jn, TS',
    to: 'Chennai Central, TN',
    departureTime: '16:50',
    arrivalTime: '05:50',
    duration: '13h 00m',
    classes: [
      { name: '2AC', availability: 40, price: 1680 },
      { name: '3AC', availability: 100, price: 1180 },
      { name: 'Sleeper', availability: 145, price: 680 },
    ],
  },
  // 17. Chennai Central <=> Pune Junction
  {
    id: 'TM1401',
    name: 'Chennai-Pune Superfast',
    number: '12164',
    from: 'Chennai Central, TN',
    to: 'Pune Junction, MH',
    departureTime: '06:45',
    arrivalTime: '05:00',
    duration: '22h 15m',
    classes: [
      { name: '2AC', availability: 30, price: 2100 },
      { name: '3AC', availability: 80, price: 1500 },
      { name: 'Sleeper', availability: 100, price: 800 },
    ],
  },
  {
    id: 'TM1401B',
    name: 'Chennai-Mumbai Express (via Pune)',
    number: '22160',
    from: 'Chennai Central, TN',
    to: 'Pune Junction, MH',
    departureTime: '13:15',
    arrivalTime: '08:10',
    duration: '18h 55m',
    classes: [
      { name: '2AC', availability: 35, price: 2120 },
      { name: '3AC', availability: 90, price: 1520 },
      { name: 'Sleeper', availability: 110, price: 810 },
    ],
  },
  {
    id: 'TM1402',
    name: 'Pune-Chennai Superfast',
    number: '12163',
    from: 'Pune Junction, MH',
    to: 'Chennai Central, TN',
    departureTime: '00:10',
    arrivalTime: '20:30',
    duration: '20h 20m',
    classes: [
      { name: '2AC', availability: 25, price: 2150 },
      { name: '3AC', availability: 70, price: 1550 },
      { name: 'Sleeper', availability: 90, price: 820 },
    ],
  },
  {
    id: 'TM1402B',
    name: 'Mumbai-Chennai Express (via Pune, Return)',
    number: '22159',
    from: 'Pune Junction, MH',
    to: 'Chennai Central, TN',
    departureTime: '16:15',
    arrivalTime: '10:45',
    duration: '18h 30m',
    classes: [
      { name: '2AC', availability: 30, price: 2180 },
      { name: '3AC', availability: 80, price: 1580 },
      { name: 'Sleeper', availability: 95, price: 830 },
    ],
  },
  // 18. Chennai Central <=> Ahmedabad Junction
  {
    id: 'TM1501',
    name: 'Navjeevan Express',
    number: '12656',
    from: 'Chennai Central, TN',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '10:10',
    arrivalTime: '18:00',
    duration: '31h 50m',
    classes: [
      { name: '2AC', availability: 40, price: 2800 },
      { name: '3AC', availability: 90, price: 1900 },
      { name: 'Sleeper', availability: 120, price: 1100 },
    ],
  },
  {
    id: 'TM1501B',
    name: 'Chennai-Ahmedabad Humsafar',
    number: '22919',
    from: 'Chennai Central, TN',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '16:00',
    arrivalTime: '21:15',
    duration: '29h 15m',
    classes: [
      { name: '3AC', availability: 130, price: 2850 },
      { name: '3AC Eco', availability: 45, price: 2500 },
    ],
  },
  {
    id: 'TM1502',
    name: 'Navjeevan Express',
    number: '12655',
    from: 'Ahmedabad Junction, GJ',
    to: 'Chennai Central, TN',
    departureTime: '07:35',
    arrivalTime: '15:25',
    duration: '31h 50m',
    classes: [
      { name: '2AC', availability: 35, price: 2850 },
      { name: '3AC', availability: 80, price: 1950 },
      { name: 'Sleeper', availability: 110, price: 1120 },
    ],
  },
  {
    id: 'TM1502B',
    name: 'Ahmedabad-Chennai Humsafar',
    number: '22920',
    from: 'Ahmedabad Junction, GJ',
    to: 'Chennai Central, TN',
    departureTime: '09:40',
    arrivalTime: '16:15',
    duration: '30h 35m',
    classes: [
      { name: '3AC', availability: 115, price: 2880 },
      { name: '3AC Eco', availability: 40, price: 2550 },
    ],
  },
  // 19. Howrah Junction <=> Bengaluru City
  {
    id: 'TM1601',
    name: 'Howrah-Bengaluru Duronto',
    number: '12245',
    from: 'Howrah Junction, WB',
    to: 'Bengaluru City, KA',
    departureTime: '10:50',
    arrivalTime: '15:50',
    duration: '29h 00m',
    classes: [
      { name: '1AC', availability: 20, price: 4200 },
      { name: '2AC', availability: 40, price: 3800 },
      { name: '3AC', availability: 100, price: 2300 },
    ],
  },
  {
    id: 'TM1601B',
    name: 'HWH-YPR Superfast',
    number: '12863',
    from: 'Howrah Junction, WB',
    to: 'Bengaluru City, KA',
    departureTime: '22:50',
    arrivalTime: '06:45',
    duration: '31h 55m',
    classes: [
      { name: '2AC', availability: 45, price: 3850 },
      { name: '3AC', availability: 110, price: 2320 },
      { name: 'Sleeper', availability: 200, price: 1300 },
    ],
  },
  {
    id: 'TM1602',
    name: 'Bengaluru-Howrah Duronto',
    number: '12246',
    from: 'Bengaluru City, KA',
    to: 'Howrah Junction, WB',
    departureTime: '11:20',
    arrivalTime: '16:40',
    duration: '29h 20m',
    classes: [
      { name: '1AC', availability: 18, price: 4250 },
      { name: '2AC', availability: 35, price: 3850 },
      { name: '3AC', availability: 90, price: 2350 },
    ],
  },
  {
    id: 'TM1602B',
    name: 'YPR-HWH Superfast',
    number: '12864',
    from: 'Bengaluru City, KA',
    to: 'Howrah Junction, WB',
    departureTime: '19:35',
    arrivalTime: '02:05',
    duration: '30h 30m',
    classes: [
      { name: '2AC', availability: 40, price: 3880 },
      { name: '3AC', availability: 95, price: 2380 },
      { name: 'Sleeper', availability: 180, price: 1320 },
    ],
  },
  // 20. Howrah Junction <=> Secunderabad Jn
  {
    id: 'TM1701',
    name: 'Falaknuma Express',
    number: '12703',
    from: 'Howrah Junction, WB',
    to: 'Secunderabad Jn, TS',
    departureTime: '07:25',
    arrivalTime: '09:35',
    duration: '26h 10m',
    classes: [
      { name: '2AC', availability: 50, price: 2500 },
      { name: '3AC', availability: 110, price: 1700 },
      { name: 'Sleeper', availability: 160, price: 950 },
    ],
  },
  {
    id: 'TM1701B',
    name: 'East Coast Express',
    number: '18645',
    from: 'Howrah Junction, WB',
    to: 'Secunderabad Jn, TS',
    departureTime: '11:45',
    arrivalTime: '18:30',
    duration: '30h 45m',
    classes: [
      { name: '2AC', availability: 55, price: 2520 },
      { name: '3AC', availability: 120, price: 1720 },
      { name: 'Sleeper', availability: 170, price: 960 },
    ],
  },
  {
    id: 'TM1702',
    name: 'Falaknuma Express',
    number: '12704',
    from: 'Secunderabad Jn, TS',
    to: 'Howrah Junction, WB',
    departureTime: '15:55',
    arrivalTime: '17:40',
    duration: '25h 45m',
    classes: [
      { name: '2AC', availability: 45, price: 2550 },
      { name: '3AC', availability: 100, price: 1750 },
      { name: 'Sleeper', availability: 150, price: 970 },
    ],
  },
  {
    id: 'TM1702B',
    name: 'East Coast Express (Return)',
    number: '18646',
    from: 'Secunderabad Jn, TS',
    to: 'Howrah Junction, WB',
    departureTime: '09:50',
    arrivalTime: '16:10',
    duration: '30h 20m',
    classes: [
      { name: '2AC', availability: 50, price: 2580 },
      { name: '3AC', availability: 110, price: 1780 },
      { name: 'Sleeper', availability: 155, price: 980 },
    ],
  },
  // 21. Howrah Junction <=> Pune Junction
  {
    id: 'TM1801',
    name: 'Azad Hind Express',
    number: '12130',
    from: 'Howrah Junction, WB',
    to: 'Pune Junction, MH',
    departureTime: '21:50',
    arrivalTime: '06:50',
    duration: '33h 00m',
    classes: [
      { name: '2AC', availability: 30, price: 2900 },
      { name: '3AC', availability: 80, price: 2000 },
      { name: 'Sleeper', availability: 110, price: 1150 },
    ],
  },
  {
    id: 'TM1801B',
    name: 'Howrah-Pune Duronto',
    number: '12222',
    from: 'Howrah Junction, WB',
    to: 'Pune Junction, MH',
    departureTime: '08:20',
    arrivalTime: '11:45',
    duration: '27h 25m',
    classes: [
      { name: '1AC', availability: 15, price: 3500 },
      { name: '2AC', availability: 35, price: 2920 },
      { name: '3AC', availability: 120, price: 1160 },
    ],
  },
  {
    id: 'TM1802',
    name: 'Azad Hind Express',
    number: '12129',
    from: 'Pune Junction, MH',
    to: 'Howrah Junction, WB',
    departureTime: '18:25',
    arrivalTime: '03:55',
    duration: '33h 30m',
    classes: [
      { name: '2AC', availability: 25, price: 2950 },
      { name: '3AC', availability: 70, price: 2050 },
      { name: 'Sleeper', availability: 100, price: 1170 },
    ],
  },
  {
    id: 'TM1802B',
    name: 'Pune-Howrah Duronto',
    number: '12221',
    from: 'Pune Junction, MH',
    to: 'Howrah Junction, WB',
    departureTime: '15:15',
    arrivalTime: '20:15',
    duration: '29h 00m',
    classes: [
      { name: '1AC', availability: 12, price: 3550 },
      { name: '2AC', availability: 30, price: 2980 },
      { name: '3AC', availability: 105, price: 1180 },
    ],
  },
  // 22. Howrah Junction <=> Ahmedabad Junction
  {
    id: 'TM1901',
    name: 'Howrah-Ahmedabad Superfast',
    number: '12834',
    from: 'Howrah Junction, WB',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '23:55',
    arrivalTime: '12:05',
    duration: '36h 10m',
    classes: [
      { name: '2AC', availability: 40, price: 3100 },
      { name: '3AC', availability: 90, price: 2100 },
      { name: 'Sleeper', availability: 130, price: 1200 },
    ],
  },
  {
    id: 'TM1901B',
    name: 'Garba Express',
    number: '12938',
    from: 'Howrah Junction, WB',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '23:00',
    arrivalTime: '06:05',
    duration: '31h 05m',
    classes: [
      { name: '2AC', availability: 45, price: 3120 },
      { name: '3AC', availability: 100, price: 2120 },
      { name: 'Sleeper', availability: 140, price: 1210 },
    ],
  },
  {
    id: 'TM1902',
    name: 'Ahmedabad-Howrah Superfast',
    number: '12833',
    from: 'Ahmedabad Junction, GJ',
    to: 'Howrah Junction, WB',
    departureTime: '00:25',
    arrivalTime: '13:30',
    duration: '37h 05m',
    classes: [
      { name: '2AC', availability: 35, price: 3150 },
      { name: '3AC', availability: 80, price: 2150 },
      { name: 'Sleeper', availability: 120, price: 1220 },
    ],
  },
  {
    id: 'TM1902B',
    name: 'Garba Express (Return)',
    number: '12937',
    from: 'Ahmedabad Junction, GJ',
    to: 'Howrah Junction, WB',
    departureTime: '23:15',
    arrivalTime: '07:00',
    duration: '31h 45m',
    classes: [
      { name: '2AC', availability: 40, price: 3180 },
      { name: '3AC', availability: 90, price: 2180 },
      { name: 'Sleeper', availability: 125, price: 1230 },
    ],
  },
  // 23. Bengaluru City <=> Secunderabad Jn
  {
    id: 'TM2001',
    name: 'Bengaluru-Secunderabad Garibrath',
    number: '12736',
    from: 'Bengaluru City, KA',
    to: 'Secunderabad Jn, TS',
    departureTime: '16:15',
    arrivalTime: '04:00',
    duration: '11h 45m',
    classes: [
      { name: '3AC', availability: 200, price: 1400 },
      { name: '3AC Eco', availability: 70, price: 1200 },
    ],
  },
  {
    id: 'TM2001B',
    name: 'Kacheguda Express',
    number: '12786',
    from: 'Bengaluru City, KA',
    to: 'Secunderabad Jn, TS',
    departureTime: '18:20',
    arrivalTime: '05:40',
    duration: '11h 20m',
    classes: [
      { name: '2AC', availability: 75, price: 1420 },
      { name: '3AC', availability: 150, price: 1000 },
      { name: 'Sleeper', availability: 210, price: 610 },
    ],
  },
  {
    id: 'TM2002',
    name: 'Secunderabad-Bengaluru Garibrath',
    number: '12735',
    from: 'Secunderabad Jn, TS',
    to: 'Bengaluru City, KA',
    departureTime: '20:30',
    arrivalTime: '08:20',
    duration: '11h 50m',
    classes: [
      { name: '3AC', availability: 190, price: 1450 },
      { name: '3AC Eco', availability: 65, price: 1250 },
    ],
  },
  {
    id: 'TM2002B',
    name: 'Kacheguda Express (Return)',
    number: '12785',
    from: 'Secunderabad Jn, TS',
    to: 'Bengaluru City, KA',
    departureTime: '19:05',
    arrivalTime: '06:25',
    duration: '11h 20m',
    classes: [
      { name: '2AC', availability: 70, price: 1480 },
      { name: '3AC', availability: 140, price: 1050 },
      { name: 'Sleeper', availability: 195, price: 630 },
    ],
  },
  // 24. Bengaluru City <=> Pune Junction
  {
    id: 'TM2101',
    name: 'Chalukya Express',
    number: '11018',
    from: 'Bengaluru City, KA',
    to: 'Pune Junction, MH',
    departureTime: '15:45',
    arrivalTime: '17:30',
    duration: '25h 45m',
    classes: [
      { name: '2AC', availability: 20, price: 1900 },
      { name: '3AC', availability: 60, price: 1300 },
      { name: 'Sleeper', availability: 90, price: 750 },
    ],
  },
  {
    id: 'TM2101B',
    name: 'Vivek Express',
    number: '19567',
    from: 'Bengaluru City, KA',
    to: 'Pune Junction, MH',
    departureTime: '11:30',
    arrivalTime: '05:00',
    duration: '17h 30m',
    classes: [
      { name: '2AC', availability: 25, price: 1920 },
      { name: '3AC', availability: 70, price: 1320 },
      { name: 'Sleeper', availability: 100, price: 760 },
    ],
  },
  {
    id: 'TM2102',
    name: 'Chalukya Express',
    number: '11017',
    from: 'Pune Junction, MH',
    to: 'Bengaluru City, KA',
    departureTime: '01:05',
    arrivalTime: '04:40',
    duration: '27h 35m',
    classes: [
      { name: '2AC', availability: 15, price: 1950 },
      { name: '3AC', availability: 50, price: 1350 },
      { name: 'Sleeper', availability: 80, price: 770 },
    ],
  },
  {
    id: 'TM2102B',
    name: 'Vivek Express (Return)',
    number: '19568',
    from: 'Pune Junction, MH',
    to: 'Bengaluru City, KA',
    departureTime: '21:15',
    arrivalTime: '15:50',
    duration: '18h 35m',
    classes: [
      { name: '2AC', availability: 20, price: 1980 },
      { name: '3AC', availability: 60, price: 1380 },
      { name: 'Sleeper', availability: 85, price: 780 },
    ],
  },
  // 25. Bengaluru City <=> Ahmedabad Junction
  {
    id: 'TM2201',
    name: 'Jodhpur Express',
    number: '16508',
    from: 'Bengaluru City, KA',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '22:20',
    arrivalTime: '08:45',
    duration: '34h 25m',
    classes: [
      { name: '2AC', availability: 25, price: 2900 },
      { name: '3AC', availability: 60, price: 2000 },
      { name: 'Sleeper', availability: 80, price: 1150 },
    ],
  },
  {
    id: 'TM2201B',
    name: 'Barmer AC Express',
    number: '14805',
    from: 'Bengaluru City, KA',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '10:30',
    arrivalTime: '18:50',
    duration: '32h 20m',
    classes: [
      { name: '1AC', availability: 10, price: 3500 },
      { name: '2AC', availability: 30, price: 2920 },
      { name: '3AC', availability: 90, price: 1160 },
    ],
  },
  {
    id: 'TM2202',
    name: 'Jodhpur Express',
    number: '16507',
    from: 'Ahmedabad Junction, GJ',
    to: 'Bengaluru City, KA',
    departureTime: '17:45',
    arrivalTime: '03:45',
    duration: '34h 00m',
    classes: [
      { name: '2AC', availability: 20, price: 2950 },
      { name: '3AC', availability: 50, price: 2050 },
      { name: 'Sleeper', availability: 70, price: 1170 },
    ],
  },
  {
    id: 'TM2202B',
    name: 'Barmer AC Express (Return)',
    number: '14806',
    from: 'Ahmedabad Junction, GJ',
    to: 'Bengaluru City, KA',
    departureTime: '07:10',
    arrivalTime: '15:20',
    duration: '32h 10m',
    classes: [
      { name: '1AC', availability: 8, price: 3550 },
      { name: '2AC', availability: 25, price: 2980 },
      { name: '3AC', availability: 75, price: 1180 },
    ],
  },
  // 26. Secunderabad Jn <=> Pune Junction
  {
    id: 'T501R',
    name: 'Secunderabad-Pune Shatabdi',
    number: '12026',
    from: 'Secunderabad Jn, TS',
    to: 'Pune Junction, MH',
    departureTime: '14:45',
    arrivalTime: '23:10',
    duration: '8h 25m',
    classes: [
      { name: '1AC', availability: 5, price: 3050 },
      { name: '2AC', availability: 25, price: 2050 },
      { name: '3AC', availability: 85, price: 1250 },
    ],
  },
  {
    id: 'T501R-B',
    name: 'Mumbai Express (via Pune)',
    number: '17032',
    from: 'Secunderabad Jn, TS',
    to: 'Pune Junction, MH',
    departureTime: '20:40',
    arrivalTime: '09:55',
    duration: '13h 15m',
    classes: [
      { name: '2AC', availability: 30, price: 1500 },
      { name: '3AC', availability: 70, price: 1000 },
      { name: 'Sleeper', availability: 95, price: 600 },
    ],
  },
  {
    id: 'T501',
    name: 'Pune-Secunderabad Shatabdi',
    number: '12025',
    from: 'Pune Junction, MH',
    to: 'Secunderabad Jn, TS',
    departureTime: '06:00',
    arrivalTime: '14:20',
    duration: '8h 20m',
    classes: [
      { name: '1AC', availability: 8, price: 3000 },
      { name: '2AC', availability: 30, price: 2000 },
      { name: '3AC', availability: 90, price: 1200 },
    ],
  },
  {
    id: 'T501-B',
    name: 'Hyderabad Express (via Pune)',
    number: '17031',
    from: 'Pune Junction, MH',
    to: 'Secunderabad Jn, TS',
    departureTime: '14:15',
    arrivalTime: '04:55',
    duration: '14h 40m',
    classes: [
      { name: '2AC', availability: 35, price: 1550 },
      { name: '3AC', availability: 80, price: 1050 },
      { name: 'Sleeper', availability: 100, price: 620 },
    ],
  },
  // 27. Secunderabad Jn <=> Ahmedabad Junction
  {
    id: 'TM2301',
    name: 'Secunderabad-Rajkot Express',
    number: '17018',
    from: 'Secunderabad Jn, TS',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '15:15',
    arrivalTime: '16:00',
    duration: '24h 45m',
    classes: [
      { name: '2AC', availability: 20, price: 2200 },
      { name: '3AC', availability: 60, price: 1500 },
      { name: 'Sleeper', availability: 90, price: 850 },
    ],
  },
  {
    id: 'TM2301B',
    name: 'Porbandar Express',
    number: '19201',
    from: 'Secunderabad Jn, TS',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '15:10',
    arrivalTime: '14:00',
    duration: '22h 50m',
    classes: [
      { name: '2AC', availability: 25, price: 2220 },
      { name: '3AC', availability: 70, price: 1520 },
      { name: 'Sleeper', availability: 100, price: 860 },
    ],
  },
  {
    id: 'TM2302',
    name: 'Rajkot-Secunderabad Express',
    number: '17017',
    from: 'Ahmedabad Junction, GJ',
    to: 'Secunderabad Jn, TS',
    departureTime: '09:20',
    arrivalTime: '10:30',
    duration: '25h 10m',
    classes: [
      { name: '2AC', availability: 15, price: 2250 },
      { name: '3AC', availability: 50, price: 1550 },
      { name: 'Sleeper', availability: 80, price: 870 },
    ],
  },
  {
    id: 'TM2302B',
    name: 'Porbandar Express (Return)',
    number: '19202',
    from: 'Ahmedabad Junction, GJ',
    to: 'Secunderabad Jn, TS',
    departureTime: '12:45',
    arrivalTime: '10:50',
    duration: '22h 05m',
    classes: [
      { name: '2AC', availability: 20, price: 2280 },
      { name: '3AC', availability: 60, price: 1580 },
      { name: 'Sleeper', availability: 85, price: 880 },
    ],
  },
  // 28. Pune Junction <=> Ahmedabad Junction
  {
    id: 'TM2401',
    name: 'Pune-Ahmedabad Duronto',
    number: '12298',
    from: 'Pune Junction, MH',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '21:35',
    arrivalTime: '06:25',
    duration: '8h 50m',
    classes: [
      { name: '1AC', availability: 10, price: 2600 },
      { name: '2AC', availability: 40, price: 2400 },
      { name: '3AC', availability: 130, price: 1300 },
    ],
  },
  {
    id: 'TM2401B',
    name: 'Ahinsa Express',
    number: '11096',
    from: 'Pune Junction, MH',
    to: 'Ahmedabad Junction, GJ',
    departureTime: '19:50',
    arrivalTime: '07:30',
    duration: '11h 40m',
    classes: [
      { name: '2AC', availability: 45, price: 1500 },
      { name: '3AC', availability: 100, price: 1000 },
      { name: 'Sleeper', availability: 140, price: 650 },
    ],
  },
  {
    id: 'TM2402',
    name: 'Ahmedabad-Pune Duronto',
    number: '12297',
    from: 'Ahmedabad Junction, GJ',
    to: 'Pune Junction, MH',
    departureTime: '22:30',
    arrivalTime: '07:15',
    duration: '8h 45m',
    classes: [
      { name: '1AC', availability: 8, price: 2650 },
      { name: '2AC', availability: 35, price: 2450 },
      { name: '3AC', availability: 120, price: 1320 },
    ],
  },
  {
    id: 'TM2402B',
    name: 'Ahinsa Express (Return)',
    number: '11095',
    from: 'Ahmedabad Junction, GJ',
    to: 'Pune Junction, MH',
    departureTime: '16:00',
    arrivalTime: '04:40',
    duration: '12h 40m',
    classes: [
      { name: '2AC', availability: 40, price: 1520 },
      { name: '3AC', availability: 90, price: 1020 },
      { name: 'Sleeper', availability: 125, price: 660 },
    ],
  },
];


// In a real application, this would be a database call.
// For this prototype, we'll just modify the in-memory array.
export function updateTrainAvailability(trainId: string, className: '1AC' | '2AC' | '3AC' | '3AC Eco' | 'Sleeper', passengers: number) {
    const train = trains.find(t => t.id === trainId);
    if (!train) return false;

    const trainClass = train.classes.find(c => c.name === className);
    if (!trainClass) return false;

    if (trainClass.availability < passengers) return false;

    trainClass.availability -= passengers;
    return true;
}
